const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');
const { icons } = require('lucide');

const root = path.resolve(__dirname, '..');
const sources = [
  'tweaks-panel', 'data', 'core', 'sections', 'traject', 'deepdive', 'scan',
  'pages', 'reviews', 'privacy', 'cookies', 'voorwaarden', 'home', 'bedankt',
  'sitemap', 'app',
];
const source = sources.map(name => fs.readFileSync(path.join(root, `${name}.jsx`), 'utf8')).join('\n');
// Import only the icons named in the source, including names in content arrays.
const names = Object.keys(icons).filter(name => {
  const kebab = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return source.includes(`"${kebab}"`) || source.includes(`'${kebab}'`);
});
const imports = `
  import React from 'react';
  import { createRoot } from 'react-dom/client';
  import { ${names.map(name => `${name} as Lucide${name}`).join(', ')} } from 'lucide';
  const ReactDOM = { createRoot };
  const lucideIcons = { ${names.map(name => `${name}: Lucide${name}`).join(', ')} };
`;
esbuild.buildSync({
  stdin: { contents: imports + source, resolveDir: root, loader: 'jsx' },
  bundle: true,
  outfile: path.join(root, 'app.bundle.js'),
  format: 'iife',
  target: 'es2018',
  minify: true,
  define: { 'process.env.NODE_ENV': '"production"' },
  legalComments: 'eof',
  banner: { js: '/* Generated by npm run build from the JSX sources. */' },
});

const dist = path.join(root, 'dist');
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist);
for (const file of fs.readdirSync(root)) {
  if ((file.endsWith('.html') && file !== 'Mobiele preview.html') || ['app.bundle.js', 'styles.css'].includes(file)) {
    fs.copyFileSync(path.join(root, file), path.join(dist, file));
  }
}
fs.cpSync(path.join(root, 'assets'), path.join(dist, 'assets'), { recursive: true });
console.log(`Built ${names.length} icons and the public site in dist/.`);
